### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by LikiPiki** [DerFreimensch/Project1#1]
Наверное тут лучше сделать константы, и использовать в структуре для определения длин строк.
https://github.com/DerFreimensch/Project1/blob/15c5c6b6beb50b070fa8dc943958151e3ba81626/Project1/Project.c#L6-L14
Тут можно обойтись одним файлом без удалений, просто закрыть исходный файл, открыть его на `w`, и полностью перезаписать содержимое
https://github.com/DerFreimensch/Project1/blob/15c5c6b6beb50b070fa8dc943958151e3ba81626/Project1/Project.c#L220-L224

А так вроде все в порядке, почему не читает последнюю запись я так и не выяснил. Если есть какие то вопросы то можно задать их в четверг в дискорде.

**Comment by kostr-code** [comment]
А так вроде все в порядке, почему не читает последнюю запись я так и не выяснил. По поводу этого понятную мне причину я тоже не выяснил, но я смог сделать так, чтобы он так не делал

**Comment by LikiPiki** [comment]
> А так вроде все в порядке, почему не читает последнюю запись я так и не выяснил. По поводу этого понятную мне причину я тоже не выяснил, но я смог сделать так, чтобы он так не делал

Хорошо что получилось
